feat: Ignore typescript error and update chat controller
- Added `@ts-expect-error` comment to handle typescript error TS6133 related to 'session' value declaration
- Simplified the 'getDocumentContent' method by removing an unused parameter in the chat service

Signed-off-by: Troy Morvant <troy.morvant@gmail.com>